### ISSUE TITLE
'1' key doesn't work on small images

### ISSUE THREAD

**Issue by nirharpaz** [Doliman100/Simple-Image-Viewer#4]
given an image smaller than screen size:
'1' doesn't fit it to screen size

**Comment by Doliman100** [comment]
This mode is needed to the image does not go out of the screen. It does the same as the built-in image viewer when zoomed out.

**Comment by nirharpaz** [comment]
so not stretching small images to fit is intended behavior?
if so I'd mention it's a bit counterintuitive comparing to the info in the plugin (i would expect both sizes to fit) and may need to add it to suggestions.

**Comment by Doliman100** [comment]
09b2a9b90b5d215cdf6e16264f581638dc995dd3 The filling type "Fit" is now allowed to stretch the image.
